Report polymorphic topEntities as errors
Instead of failing somewhere inside netlist generation with some unhelpful error like:
	Clash.Netlist.Util(...): Not in normal form: ...

Clash will now say:
	tests/shouldfail/Poly.hs:4:1: error:
	    Clash.Normalize(179): Clash can only normalize monomorphic functions, but this is polymorphic:

	Poly.topEntity :: forall (p :: GHC.Prim.TYPE
        	                         GHC.Types.LiftedRep).
	              GHC.Types.Bool -> p -> GHC.Types.Bool