Show nicer error messages when failing in TH code
..by using fail instead of error.

Example:
-------------------------------------------------------
AutoReg.hs:66:1: error: No custom bit annotation found.
   |
66 | deriveBitPack [t|Bool|]
   | ^
-------------------------------------------------------

Instead of:
-------------------------------------------------------
AutoReg.hs:1:1: error:
    Exception when trying to run compile-time code:
      No custom bit annotation found.
CallStack (from HasCallStack):
  error, called at
src/Clash/Annotations/BitRepresentation/Deriving.hs:905:22 in
clash-prelude-1.1.0-inplace:Clash.Annotations.BitRepresentation.Deriving
    Code: deriveBitPack [t| Bool |]
  |
1 | {-# LANGUAGE ConstrainedClassMethods #-}
  | ^
-------------------------------------------------------